map_names = {
    0x0: "Overworld",
    0x1: "Earth Cave B1",
    0x2: "Earth Cave B2",
    0x3: "Earth Cave B3",
    0x4: "Earth Cave B4",
    0x5: "Earth Cave B5",
    0x6: "Elven Castle",
    0x7: "Elfheim",
    0x8: "Elfheim Inn",
    0x9: "Elfheim Weapon Shop",
    0xa: "Elfheim Armor Shop",
    0xb: "Elfheim Item Shop",
    0xc: "Elfheim White Magic 1",
    0xd: "Elfheim White Magic 2",
    0xe: "Elfheim Black Magic 1",
    0xf: "Elfheim Black Magic 2",
    0x10: "Elfheim Chapel",
    0x11: "Onrac",
    0x12: "Onrac Inn",
    0x13: "Onrac Item Shop",
    0x14: "Onrac White Magic",
    0x15: "Onrac Black Magic",
    0x16: "Onrac Chapel",
    0x17: "Sunken Shrine 1F",
    0x18: "Sunken Shrine 2F",
    0x19: "Sunken Shrine 3Fa",
    0x1a: "Sunken Shrine 3Fb",
    0x1b: "Sunken Shrine 3Fc",
    0x1c: "Sunken Shrine 4Fa",
    0x1d: "Sunken Shrine 4Fb",
    0x1e: "Sunken Shrine 5F",
    0x1f: "Chaos Shrine",
    0x20: "Chaos Temple 1F",
    0x21: "Chaos Temple 2F",
    0x22: "Chaos Temple 3F",
    0x23: "Chaos Temple B1",
    0x24: "Chaos Temple B2",
    0x25: "Chaos Temple B3",
    0x26: "Chaos Temple B4",
    0x27: "Chaos Temple B5",
    0x28: "Giants Cave",
    0x29: "Mt Gulg B1",
    0x2a: "Mt Gulg B2",
    0x2b: "Mt Gulg B3",
    0x2c: "Mt Gulg B3a",
    0x2d: "Mt Gulg B4",
    0x2e: "Mt Gulg B5",
    0x2f: "Crescent Lake",
    0x30: "Crescent Lake Inn",
    0x31: "Crescent Lake Weapon Shop",
    0x32: "Crescent Lake Armor Shop",
    0x33: "Crescent Lake Item Shop",
    0x34: "Crescent Lake White Magic",
    0x35: "Crescent Lake Black Magic",
    0x36: "Crescent Lake Chapel",
    0x37: "Sages Cave",
    0x38: "Castle Cornelia 1F",
    0x39: "Castle Cornelia 2F",
    0x3a: "Cornelia",
    0x3b: "Cornelia Inn",
    0x3c: "Cornelia Weapon Shop",
    0x3d: "Cornelia Armor Shop",
    0x3e: "Cornelia Item Shop",
    0x3f: "Cornelia White Magic",
    0x40: "Cornelia Black Magic",
    0x41: "Cornelia Chapel",
    0x42: "Cavern of Ice B1",
    0x43: "Cavern of Ice B2a",
    0x44: "Cavern of Ice B2b",
    0x45: "Cavern of Ice B3a",
    0x46: "Cavern of Ice B3b",
    0x47: "Gaia",
    0x48: "Gaia Inn",
    0x49: "Gaia WeaponArmor Shop",
    0x4a: "Gaia Item Shop",
    0x4b: "Gaia WhiteBlack Magic",
    0x4c: "Gaia Chapel",
    0x4d: "Citadel of Trials 1F",
    0x4e: "Citadel of Trials 2F",
    0x4f: "Citadel of Trials 3F",
    0x50: "Mirage Tower 1F",
    0x51: "Mirage Tower 2F",
    0x52: "Mirage Tower 3F",
    0x53: "Waterfall Cavern",
    0x54: "Dragon Caves B2",
    0x55: "Dragon Caves B1 Bahamuts",
    0x56: "Dragon Caves B1",
    0x57: "Mt Duergar",
    0x58: "Western Keep",
    0x59: "Marsh Cave B1",
    0x5a: "Marsh Cave B2",
    0x5b: "Marsh Cave B3",
    0x5c: "Flying Fortress 1F",
    0x5d: "Flying Fortress 2F",
    0x5e: "Flying Fortress 3F",
    0x5f: "Flying Fortress 4F",
    0x60: "Flying Fortress 5F",
    0x61: "Matoyas Cave",
    0x62: "Pravoka",
    0x63: "Pravoka Inn",
    0x64: "Pravoka Weapon Shop",
    0x65: "Pravoka Armor Shop",
    0x66: "Pravoka Item Shop",
    0x67: "Pravoka White Magic",
    0x68: "Pravoka Black Magic",
    0x69: "Pravoka Chapel",
    0x6a: "Melmond",
    0x6b: "Melmond Inn",
    0x6c: "Melmond Weapon Shop",
    0x6d: "Melmond Armor Shop",
    0x6e: "Melmond White Magic",
    0x6f: "Melmond Black Magic",
    0x70: "Lufenia",
    0x71: "Lufenia WhiteBlack Magic",
    0x72: "Caravan",
    0x73: "Caravan Interior",
    0x74: "Gaia White Magic 2",
    0x75: "Gaia Black Magic 2",
    0x76: "Drawbridge cutscene",
    0x77: "Ryukahn Desert cutscene",
    0x78: "Earthgift Shrine Entrance",
    0x79: "Hellfire Chasm Entrance",
    0x7a: "Lifespring Grotto Entrance",
    0x7b: "Whisperwind Cove Entrance",
}

flag_names = {
    0x1: "Garland_Defeated",
    0x2: "Bridge_Commissioned",
    0x3: "Bridge",
    0x4: "Lute",
    0x5: "Ship",
    0x6: "Crown",
    0x7: "Crystal",
    0x8: "Jolt_Tonic",
    0x9: "Mystic_Key",
    0xa: "Nitro_Powder",
    0xb: "Canal",
    0xc: "Defeated_Vampire",
    0xd: "Star_Ruby",
    0xe: "Fed_Titan",
    0xf: "Rod",
    0x10: "Broke_Stone_Slab",
    0x11: "Earth",
    0x12: "Canoe",
    0x13: "Fire",
    0x14: "Levistone",
    0x15: "Airship",
    0x17: "Rats_Tail",
    0x18: "Promotion",
    0x1a: "Oxyale",
    0x1c: "Rosetta_Stone",
    0x1d: "Water",
    0x1e: "Lufienish",
    0x1f: "Chime",
    0x20: "Warp_Cube",
    0x21: "Adamantite",
    0x22: "Air",
    0x23: "Excalibur",
    0x24: "Warp_Gate_Open",
    0x28: "Guards",
    0x29: "Watched_Bridge_Credits",
}

sprite_id_to_name = {
    0x0: "Princess_Sarah",
    0x1: "Woman_green",
    0x2: "Woman_purple",
    0x3: "Elderly_Woman",
    0x4: "Dancer_blue",
    0x5: "Dancer_pink",
    0x6: "Dancer_blonde",
    0x7: "Dancer_green",
    0x8: "Dancer_navy",
    0x9: "Dancer_cyan",
    0xa: "Orb_dark",
    0xb: "Witch_red",
    0xc: "Barrel_Girl",
    0xd: "Soldier",
    0xe: "Scholar_yellow",
    0xf: "Scholar_cyan",
    0x10: "Scholar_gray",
    0x11: "Scholar_purple",
    0x12: "Scholar_blonde",
    0x13: "Scholar_brown",
    0x14: "Mohawk_Dude_1",
    0x15: "Mohawk_Dude_2",
    0x16: "Mohawk_Dude_3",
    0x17: "Man_Blue",
    0x18: "Old_Man",
    0x19: "Dwarf",
    0x1a: "Mermaid_purple",
    0x1b: "Mermaid_pink",
    0x1c: "Mermaid_green",
    0x1d: "Mermaid_blue",
    0x1e: "Mermaid_red",
    0x1f: "Mermaid_cyan",
    0x20: "Mermaid_submerged",
    0x21: "Lufenian",
    0x22: "King_Cornelia",
    0x23: "King_Undead",
    0x24: "Broom",
    0x25: "Bat",
    0x26: "Garland",
    0x27: "Pirate_red",
    0x28: "Pirate_blue",
    0x29: "Fairy",
    0x2a: "Fairy_evil",
    0x2b: "Robot",
    0x2c: "Robot_pink",
    0x2d: "Dragon",
    0x2e: "Black_Mage_vendor",
    0x2f: "Elf_Doctor",
    0x30: "Elf",
    0x31: "Elven_Prince",
    0x32: "Earth_Cave_Slab",
    0x33: "White_Mage_vendor",
    0x34: "Vampire_Bat",
    0x35: "Item_Vendor",
    0x36: "Black_Wizard_vendor",
    0x37: "Matoya",
    0x38: "Lukahn",
    0x39: "Sadda",
    0x3a: "Unne",
    0x3b: "Nerrick",
    0x3c: "Smyth",
    0x3d: "Little_Princess",
    0x3e: "Queen_Jayne",
    0x3f: "Queen_Undead",
    0x40: "Weapons_Vendor",
    0x41: "Armor_Vendor",
    0x42: "Woman_Vendor",
    0x43: "Priest",
    0x44: "Underhill",
    0x45: "Bikke",
    0x46: "White_Wizard_Vendor",
    0x47: "King_Astos",
    0x48: "Astos",
    0x49: "Chapel_Angel",
    0x4a: "Light",
    0x4b: "Ladder",
    0x4c: "Smyths_Hammer",
    0x4d: "Malfunctioning_Robot",
    0x4e: "Elven_Seer",
    0x4f: "Orb_Dark_Green",
    0x50: "Orb_Dark_Blue",
    0x51: "Orb_Dark_Yellow",
    0x52: "Orb_Dark_Red",
    0x53: "Orb_Green",
    0x54: "Orb_Blue",
    0x55: "Orb_Yellow",
    0x56: "Orb_Red",
    0x57: "Levistone",
    0x58: "Star_Ruby",
    0x59: "Adamantite",
    0x5a: "Excalibur",
    0x5b: "Barrel_Submarine",
    0x5c: "Chancellor",
    0x5d: "Lich_Statue",
    0x5e: "Kraken_Statue",
    0x5f: "Marilith_Statue",
    0x60: "Tiamat_Statue",
    0x61: "Sleeping_Bag",
    0x62: "Tent",
    0x63: "Cottage",
    0x64: "Bahamut",
    0x65: "Bahamut_Dark",
    0x66: "Giant",
    0x67: "Lich",
    0x68: "Marilith",
    0x69: "Kraken",
    0x6a: "Tiamat",
    0x6b: "Chaos",
    0x6c: "Earth_Crystal",
    0x6d: "Fire_Crystal",
    0x6e: "Water_Crystal",
    0x6f: "Wind_Crystal",
    0x70: "Earth_Crystal_lit",
    0x71: "Fire_Crystal_lit",
    0x72: "Water_Crystal_lit",
    0x73: "Wind_Crystal_lit",
    0x74: "Warp_Green",
    0x75: "Warp_Blue",
    0x76: "Warp_Yellow",
    0x77: "Warp_Red",
    0x78: "Warp_Light_Green",
    0x79: "Warp_Light_Blue",
    0x7a: "Warp_Light_Yellow",
    0x7b: "Warp_Light_Red",
    0x7c: "Soul_Blue",
    0x7d: "Soul_Purple",
    0x7e: "Palm_Tree",
    0x7f: "Kid_Yellow",
    0x80: "Kid_Green",
    0x81: "Kid_Red",
    0x82: "Kid_Black",
    0x83: "Kid_Blue",
    0x84: "Kid_Brown",
    0x85: "Broken_Robot",
    0x86: "Beaver",
    0x87: "Woman_Undead",
    0x88: "Soldier_Undead",
    0x89: "Mohawk_Dude_Undead",
    0x8a: "Man_Undead",
    0x8b: "Elderly_Man_Undead",
    0x8c: "Woman_Stone",
    0x8d: "Man_Stone",
    0x8e: "Soldier_Stone",
    0x8f: "Red_Wizard_Pink",
    0x90: "Red_Wizard_Green",
    0x91: "White_Wizard_Red",
    0x92: "White_Wizard_Blue",
    0x93: "Black_Wizard_Green",
    0x94: "Black_Wizard_Black",
    0x95: "Warrior",
    0x96: "Knight",
    0x97: "Thief",
    0x98: "Ninja",
    0x99: "Monk",
    0x9a: "Master",
    0x9b: "Red_Mage",
    0x9c: "Red_Wizard",
    0x9d: "White_Mage",
    0x9e: "White_Wizard",
    0x9f: "Black_Mage",
    0xa0: "Black_Wizard",
    0xa1: "Canoe_1",
    0xa2: "Canoe_2",
    0xa3: "Canoe_3",
    0xa4: "Ship_1",
    0xa5: "Ship_2",
    0xa6: "Ship_3",
    0xa7: "Ship_4_brown",
    0xa8: "Ship_5_black",
    0xa9: "Ship_6_light",
    0xaa: "Ship_7_purple",
    0xab: "Ship_8",
    0xac: "Airship_landed",
    0xad: "Airship_flying",
    0xae: "Airship_takeoff",
    0xaf: "Airship_landing",
    0xb0: "Small_Water_Crystal",
    0xb1: "Small_Fire_Crystal",
    0xb2: "Small_Wind_Crystal",
    0xb3: "Small_Earth_Crystal",
    0xb4: "Bubble",
    0xb5: "Pink_Sparkles",
    0xb6: "Splash",
    0xb7: "Broken_Ice_Floor",
    0xb8: "Citadel_Warp_Effect",
    0xb9: "Pink_Light",
    0xba: "Twin_Pink_Lights",
    0xbb: "Falling_Sparkles",
    0xbc: "Castle_Cornelia",
    0xbd: "Chaos_Shrine",
    0xbe: "Elven_Castle",
    0xbf: "Citadel_of_Trials",
    0xc0: "Mirage_Tower",
    0xc1: "Western_Keep",
    0xc2: "Cloud_1",
    0xc3: "Cloud_2_sunset",
    0xc4: "FINAL_FANTASY",
    0xc5: "Warp_Black",
    0xc6: "Tiny_Splash",
    0xc7: "Chest_Closed",
}

key_item_names = {
    0x0: "Lute",
    0x1: "Crown",
    0x2: "Crystal",
    0x3: "Jolt_Tonic",
    0x4: "Mystic_Key",
    0x5: "Nitro_Powder",
    0x6: "Adamantite",
    0x7: "Rosetta_Stone",
    0x8: "Star_Ruby",
    0x9: "Rod",
    0xa: "Levistone",
    0xb: "Chime",
    0xc: "Rats_Tail",
    0xd: "Warp_Cube",
    0xf: "Oxyale",
    0x10: "Canoe",
    0x11: "Excalibur",
}


def get_flag_name(flag: int) -> str:
    if flag in flag_names:
        return f"%Flag_{flag_names[flag]}_{hex(flag)}"
    return hex(flag)


def get_map_var_name(map_id: int) -> str:
    if map_id in map_names:
        name = map_names[map_id].replace(" ", "_")
        return f"%Map_{name}_{hex(map_id)}"
    return hex(map_id)


def get_key_item_name(ki: int) -> str:
    if ki in key_item_names:
        return f"%Item_{key_item_names[ki]}_{hex(ki)}"
    return hex(ki)


def get_map_name(map_id: int) -> str:
    if map_id in map_names:
        return map_names[map_id].replace(" ", "_")
    return hex(map_id)


def get_sprite_name(sprite_id: int) -> str:
    if sprite_id in sprite_id_to_name:
        return sprite_id_to_name[sprite_id].replace(" ", "_")
    return hex(sprite_id)
