; ; Map initialization code for Overworld
begin script=0x0
	if %Flag_Watched_Bridge_Credits_0x29 unset goto .Label_1_Flag_Watched_Bridge_Credits_0x29_Unset
	remove_trigger %Event_Bridge_Credits
	.Label_1_Flag_Watched_Bridge_Credits_0x29_Unset:
	if %Flag_Airship_0x15 unset goto .Label_2_Flag_Airship_0x15_Unset
	remove_trigger %Event_Airship_Rises_From_Ryukahn_Desert
	.Label_2_Flag_Airship_0x15_Unset:
	if %Flag_Chime_0x1f set goto .Label_3_Flag_Chime_0x1f_Set
	db 0x2f 0x8 0x0 0x0 0xff 0xb8 0x38 0x2
	.Label_3_Flag_Chime_0x1f_Set:
	npc_update 0x4 %NPC_Castle_Cornelia_0x0
	npc_update 0x4 %NPC_Chaos_Shrine_0x1
	npc_update 0x4 %NPC_Elven_Castle_0x2
	npc_update 0x4 %NPC_Citadel_of_Trials_0x3
	npc_update 0x4 %NPC_Western_Keep_0x4
	npc_update 0x4 %NPC_Mirage_Tower_0x5
	end_event


; ; Map initialization code for Earth Cave B1
begin script=0x1
	end_event


; ; Map initialization code for Earth Cave B2
begin script=0x2
	end_event


; ; Map initialization code for Earth Cave B3
begin script=0x3
	db 0x18 0x8 0xe 0x1 0x2 0x0 0xff 0xff
	if %Flag_Star_Ruby_0xd unset goto .Label_1_Flag_Star_Ruby_0xd_Unset
	remove_all %Event_Star_Ruby_Chest
	.Label_1_Flag_Star_Ruby_0xd_Unset:
	if %Flag_Defeated_Vampire_0xc unset goto .Label_2_Flag_Defeated_Vampire_0xc_Unset
	remove_trigger %Event_Confronting_Vampire
	.Label_2_Flag_Defeated_Vampire_0xc_Unset:
	if %Flag_Broke_Stone_Slab_0x10 unset goto .Label_3_Flag_Broke_Stone_Slab_0x10_Unset
	remove_trigger %Event_Earth_Cave_B3_Slab
	goto .Label_4
	.Label_3_Flag_Broke_Stone_Slab_0x10_Unset:
	if %Flag_Rod_0xf unset goto .Label_4
	set_npc_event %NPC_Earth_Cave_Slab_0xe 0x139c
	.Label_4:
	end_event


; ; Map initialization code for Earth Cave B4
begin script=0x4
	end_event


; ; Map initialization code for Earth Cave B5
begin script=0x5
	if %Flag_Earth_0x11 unset goto .Label_1_Flag_Earth_0x11_Unset
	remove_all %Event_Confronting_Lich
	remove_npc %NPC_Earth_Crystal_0xb 0x0
	remove_npc %NPC_Warp_Yellow_0xd 0x0
	npc_update 0x4 %NPC_Warp_Light_Yellow_0xf
	goto .Label_2
	.Label_1_Flag_Earth_0x11_Unset:
	db 0x18 0x8 0xc 0x1 0xf8 0xff 0xff 0xff
	npc_update 0x2 %NPC_Lich_0xc
	npc_update 0x4 %NPC_Lich_0xc
	npc_update 0x4 %NPC_Warp_Yellow_0xd
	db 0x1c 0x4 0xd 0x3
	npc_update 0x2 %NPC_Earth_Crystal_lit_0xe
	npc_update 0x2 %NPC_Warp_Light_Yellow_0xf
	npc_update 0x4 %NPC_Warp_Light_Yellow_0xf
	db 0x18 0x8 0xb 0x1 0xfc 0xff 0xff 0xff
	.Label_2:
	db 0x18 0x8 0xe 0x1 0xfc 0xff 0xff 0xff
	db 0x1c 0x4 0xf 0x3
	end_event


; ; Map initialization code for Elven Castle
begin script=0x6
	if %Flag_Mystic_Key_0x9 unset goto .Label_1_Flag_Mystic_Key_0x9_Unset
	move_npc %NPC_Elven_Prince_0x7 0 17 15
	remove_trigger %Event_Mystic_Key_Door
	remove_trigger %Event_Mystic_Key_Vault
	goto .Label_2
	.Label_1_Flag_Mystic_Key_0x9_Unset:
	set_npc_frame %NPC_Elven_Prince_0x7 0x8
	if %Flag_Jolt_Tonic_0x8 unset goto .Label_2
	set_npc_event %NPC_Elf_Doctor_0x6 0x139a
	goto .Label_2
	.Label_2:
	end_event


; ; Map initialization code for Elfheim
begin script=0x7
	end_event


; ; Map initialization code for Elfheim Inn
begin script=0x8
	end_event


; ; Map initialization code for Elfheim Weapon Shop
begin script=0x9
	end_event


; ; Map initialization code for Elfheim Armor Shop
begin script=0xa
	end_event


; ; Map initialization code for Elfheim Item Shop
begin script=0xb
	end_event


; ; Map initialization code for Elfheim White Magic 1
begin script=0xc
	end_event


; ; Map initialization code for Elfheim White Magic 2
begin script=0xd
	end_event


; ; Map initialization code for Elfheim Black Magic 1
begin script=0xe
	end_event


; ; Map initialization code for Elfheim Black Magic 2
begin script=0xf
	end_event


; ; Map initialization code for Elfheim Chapel
begin script=0x10
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Onrac
begin script=0x11
	if %Flag_Oxyale_0x1a unset goto .Label_1_Flag_Oxyale_0x1a_Unset
	set_npc_event %NPC_Barrel_Girl_0xb 0x13a1
	.Label_1_Flag_Oxyale_0x1a_Unset:
	if 0x1b unset goto .Label_2_0x1b_Unset
	remove_trigger %Event_Sub_Engineer_Fades_Away
	.Label_2_0x1b_Unset:
	db 0x1c 0x4 0xf 0x3
	end_event


; ; Map initialization code for Onrac Inn
begin script=0x12
	end_event


; ; Map initialization code for Onrac Item Shop
begin script=0x13
	end_event


; ; Map initialization code for Onrac White Magic
begin script=0x14
	end_event


; ; Map initialization code for Onrac Black Magic
begin script=0x15
	end_event


; ; Map initialization code for Onrac Chapel
begin script=0x16
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Sunken Shrine 1F
begin script=0x17
	if %Flag_Water_0x1d unset goto .Label_1_Flag_Water_0x1d_Unset
	remove_all %Event_Confronting_Kraken
	remove_npc %NPC_Water_Crystal_0x1 0x0
	remove_npc %NPC_Warp_Blue_0x2 0x0
	npc_update 0x4 %NPC_Warp_Light_Blue_0x5
	goto .Label_2
	.Label_1_Flag_Water_0x1d_Unset:
	db 0x18 0x8 0x3 0x1 0xf8 0xff 0xff 0xff
	npc_update 0x2 %NPC_Kraken_0x3
	npc_update 0x4 %NPC_Kraken_0x3
	npc_update 0x4 %NPC_Warp_Blue_0x2
	db 0x1c 0x4 0x2 0x3
	npc_update 0x2 %NPC_Water_Crystal_lit_0x4
	npc_update 0x2 %NPC_Warp_Light_Blue_0x5
	npc_update 0x4 %NPC_Warp_Light_Blue_0x5
	db 0x18 0x8 0x1 0x1 0xfc 0xff 0xff 0xff
	db 0x1c 0x4 0x1 0x1
	.Label_2:
	db 0x18 0x8 0x4 0x1 0xfc 0xff 0xff 0xff
	db 0x1c 0x4 0x5 0x3
	db 0x1c 0x4 0x4 0x1
	end_event


; ; Map initialization code for Sunken Shrine 2F
begin script=0x18
	end_event


; ; Map initialization code for Sunken Shrine 3Fa
begin script=0x19
	npc_update 0x4 %NPC_Barrel_Submarine_0x1
	set_npc_event %NPC_Barrel_Submarine_0x0 0x13b2
	npc_update 0x4 %NPC_Ladder_0x2
	npc_update 0x4 %NPC_Ladder_0x3
	npc_update 0x4 %NPC_Ladder_0x4
	npc_update 0x4 %NPC_Ladder_0x5
	db 0x1c 0x4 0x2 0x3
	db 0x1c 0x4 0x3 0x3
	db 0x1c 0x4 0x4 0x3
	db 0x1c 0x4 0x5 0x3
	db 0x1c 0x4 0x0 0x3
	db 0x1c 0x4 0x1 0x3
	end_event


; ; Map initialization code for Sunken Shrine 3Fb
begin script=0x1a
	end_event


; ; Map initialization code for Sunken Shrine 3Fc
begin script=0x1b
	end_event


; ; Map initialization code for Sunken Shrine 4Fa
begin script=0x1c
	end_event


; ; Map initialization code for Sunken Shrine 4Fb
begin script=0x1d
	end_event


; ; Map initialization code for Sunken Shrine 5F
begin script=0x1e
	if %Flag_Rosetta_Stone_0x1c unset goto .Label_1_Flag_Rosetta_Stone_0x1c_Unset
	remove_all %Event_Rosetta_Stone_Chest
	.Label_1_Flag_Rosetta_Stone_0x1c_Unset:
	end_event


; ; Map initialization code for Chaos Shrine
begin script=0x1f
	if %Flag_Guards_0x28 set goto .Label_1_Flag_Guards_0x28_Set
	db 0x2f 0x8 0x4d 0x1f 0xff 0x26 0x23 0x2
	goto .Label_2
	.Label_1_Flag_Guards_0x28_Set:
	if %Flag_Garland_Defeated_0x1 unset goto .Label_3_Flag_Garland_Defeated_0x1_Unset
	remove_trigger %Event_Confronting_Garland_And_Sarah_Rescue
	remove_trigger %Event_Confronting_Garland_And_Sarah_Rescue
	if %Flag_Mystic_Key_0x9 unset goto .Label_2
	remove_trigger %Event_Mystic_Key_Door
	remove_trigger %Event_Mystic_Key_Door
	goto .Label_2
	.Label_3_Flag_Garland_Defeated_0x1_Unset:
	db 0x2f 0x8 0x0 0x0 0xff 0x25 0x1c 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0x25 0x1d 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0x27 0x1c 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0x27 0x1d 0x8
	db 0x21 0x4 0x6 0x4
	.Label_2:
	if %Flag_Warp_Gate_Open_0x24 unset goto .Label_4_Flag_Warp_Gate_Open_0x24_Unset
	remove_trigger %Event_Black_Crystal
	goto .Label_5
	.Label_4_Flag_Warp_Gate_Open_0x24_Unset:
	if %Flag_Fire_0x13 unset goto .Label_5
	if %Flag_Water_0x1d unset goto .Label_5
	if %Flag_Air_0x22 unset goto .Label_5
	set_npc_event %NPC_Orb_dark_0x7 0x13a0
	db 0x2f 0x8 0x0 0x0 0xff 0x25 0x1c 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0x27 0x1c 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0x26 0x1d 0x8
	.Label_5:
	end_event


; ; Map initialization code for Chaos Temple 1F
begin script=0x20
	npc_update 0x4 %NPC_Warp_Black_0x0
	db 0x1c 0x4 0x0 0x3
	end_event


; ; Map initialization code for Chaos Temple 2F
begin script=0x21
	end_event


; ; Map initialization code for Chaos Temple 3F
begin script=0x22
	db 0x18 0x8 0x0 0x1 0x3 0x0 0xff 0xff
	if 0x25 unset goto .Label_1_0x25_Unset
	remove_trigger %Event_Lutesealed_Slab
	goto .Label_2
	.Label_1_0x25_Unset:
	set_npc_event %NPC_Earth_Cave_Slab_0x0 0x13ab
	.Label_2:
	end_event


; ; Map initialization code for Chaos Temple B1
begin script=0x23
	end_event


; ; Map initialization code for Chaos Temple B2
begin script=0x24
	end_event


; ; Map initialization code for Chaos Temple B3
begin script=0x25
	end_event


; ; Map initialization code for Chaos Temple B4
begin script=0x26
	end_event


; ; Map initialization code for Chaos Temple B5
begin script=0x27
	npc_update 0x2 %NPC_Chaos_0x5
	npc_update 0x4 %NPC_Chaos_0x5
	db 0x18 0x8 0x1 0x1 0xfc 0xff 0xff 0xff
	db 0x18 0x8 0x2 0x1 0xfc 0xff 0xff 0xff
	db 0x18 0x8 0x3 0x1 0xfc 0xff 0xff 0xff
	db 0x18 0x8 0x4 0x1 0xfc 0xff 0xff 0xff
	end_event


; ; Map initialization code for Giants Cave
begin script=0x28
	db 0x18 0x8 0x0 0x1 0xf8 0xff 0xff 0xff
	db 0x18 0x8 0x0 0x0 0xf8 0xff 0xff 0xff
	if 0xe unset goto .Label_1_0xe_Unset
	remove_trigger %Event_Talking_To_Giant
	goto .Label_2
	.Label_1_0xe_Unset:
	if %Flag_Star_Ruby_0xd unset goto .Label_2
	set_npc_event %NPC_Giant_0x0 0x1399
	.Label_2:
	end_event


; ; Map initialization code for Mt Gulg B1
begin script=0x29
	end_event


; ; Map initialization code for Mt Gulg B2
begin script=0x2a
	end_event


; ; Map initialization code for Mt Gulg B3
begin script=0x2b
	end_event


; ; Map initialization code for Mt Gulg B3a
begin script=0x2c
	end_event


; ; Map initialization code for Mt Gulg B4
begin script=0x2d
	end_event


; ; Map initialization code for Mt Gulg B5
begin script=0x2e
	if %Flag_Fire_0x13 unset goto .Label_1_Flag_Fire_0x13_Unset
	remove_all %Event_Confronting_Marilith
	remove_npc %NPC_Fire_Crystal_0x3 0x0
	remove_npc %NPC_Warp_Red_0x2 0x0
	npc_update 0x4 %NPC_Warp_Light_Red_0x4
	goto .Label_2
	.Label_1_Flag_Fire_0x13_Unset:
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	npc_update 0x2 %NPC_Marilith_0x1
	npc_update 0x4 %NPC_Marilith_0x1
	npc_update 0x4 %NPC_Warp_Red_0x2
	db 0x1c 0x4 0x2 0x3
	npc_update 0x2 %NPC_Fire_Crystal_lit_0x5
	npc_update 0x2 %NPC_Warp_Light_Red_0x4
	npc_update 0x4 %NPC_Warp_Light_Red_0x4
	db 0x18 0x8 0x3 0x1 0xfc 0xff 0xff 0xff
	.Label_2:
	db 0x18 0x8 0x5 0x1 0xfc 0xff 0xff 0xff
	db 0x1c 0x4 0x4 0x3
	end_event


; ; Map initialization code for Crescent Lake
begin script=0x2f
	if %Flag_Fire_0x13 unset goto .Label_1_Flag_Fire_0x13_Unset
	goto .Label_2
	.Label_1_Flag_Fire_0x13_Unset:
	if %Flag_Canoe_0x12 set goto .Label_2
	if %Flag_Earth_0x11 unset goto .Label_2
	set_npc_event %NPC_Old_Man_0xc 0x1394
	goto .Label_2
	.Label_2:
	end_event


; ; Map initialization code for Crescent Lake Inn
begin script=0x30
	end_event


; ; Map initialization code for Crescent Lake Weapon Shop
begin script=0x31
	end_event


; ; Map initialization code for Crescent Lake Armor Shop
begin script=0x32
	end_event


; ; Map initialization code for Crescent Lake Item Shop
begin script=0x33
	end_event


; ; Map initialization code for Crescent Lake White Magic
begin script=0x34
	end_event


; ; Map initialization code for Crescent Lake Black Magic
begin script=0x35
	end_event


; ; Map initialization code for Crescent Lake Chapel
begin script=0x36
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Sages Cave
begin script=0x37
	if %Flag_Rod_0xf set goto .Label_1_Flag_Rod_0xf_Set
	set_npc_event %NPC_Sadda_0x0 0x13b8
	.Label_1_Flag_Rod_0xf_Set:
	end_event


; ; Map initialization code for Castle Cornelia 1F
begin script=0x38
	if %Flag_Bridge_0x3 unset goto .Label_1_Flag_Bridge_0x3_Unset
	remove_all %Event_Bridge_Rebuilding_Scene
	goto .Label_2
	.Label_1_Flag_Bridge_0x3_Unset:
	if %Flag_Garland_Defeated_0x1 unset goto .Label_3_Flag_Garland_Defeated_0x1_Unset
	goto .Label_2
	.Label_3_Flag_Garland_Defeated_0x1_Unset:
	remove_all %Event_Bridge_Rebuilding_Scene
	.Label_2:
	if %Flag_Nitro_Powder_0xa unset goto .Label_4_Flag_Nitro_Powder_0xa_Unset
	remove_all %Event_Nitro_Powder_Chest
	.Label_4_Flag_Nitro_Powder_0xa_Unset:
	if %Flag_Mystic_Key_0x9 unset goto .Label_5_Flag_Mystic_Key_0x9_Unset
	remove_trigger %Event_Mystic_Key_Door
	remove_trigger %Event_Mystic_Key_Door
	remove_all %Event_Mystic_Key_Vault
	.Label_5_Flag_Mystic_Key_0x9_Unset:
	end_event


; ; Map initialization code for Castle Cornelia 2F
begin script=0x39
	if %Flag_Guards_0x28 unset goto .Label_1_Flag_Guards_0x28_Unset
	remove_all %Event_Cornelian_Soldiers_Teleport_To_The_King
	goto .Label_2
	.Label_1_Flag_Guards_0x28_Unset:
	remove_trigger %Event_Cornelia_Castle_Guard_Throne_Room
	.Label_2:
	set_npc_frame %NPC_King_Cornelia_0x2 0x0
	if %Flag_Garland_Defeated_0x1 set goto .Label_3_Flag_Garland_Defeated_0x1_Set
	remove_trigger %Event_Talking_To_Princess_Sarah
	goto .Label_4
	.Label_3_Flag_Garland_Defeated_0x1_Set:
	if %Flag_Lute_0x4 set goto .Label_4
	db 0x2f 0x8 0xcb 0x13 0xff 0x14 0xa 0x8
	.Label_4:
	end_event


; ; Map initialization code for Cornelia
begin script=0x3a
	if %Flag_Guards_0x28 unset goto .Label_1_Flag_Guards_0x28_Unset
	remove_trigger %Event_Cornelian_Soldiers_Teleport_To_The_King
	remove_trigger %Event_Cornelian_Soldiers_Teleport_To_The_King
	remove_trigger %Event_Cornelian_Soldiers_Teleport_To_The_King
	.Label_1_Flag_Guards_0x28_Unset:
	end_event


; ; Map initialization code for Cornelia Inn
begin script=0x3b
	end_event


; ; Map initialization code for Cornelia Weapon Shop
begin script=0x3c
	end_event


; ; Map initialization code for Cornelia Armor Shop
begin script=0x3d
	end_event


; ; Map initialization code for Cornelia Item Shop
begin script=0x3e
	end_event


; ; Map initialization code for Cornelia White Magic
begin script=0x3f
	end_event


; ; Map initialization code for Cornelia Black Magic
begin script=0x40
	end_event


; ; Map initialization code for Cornelia Chapel
begin script=0x41
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Cavern of Ice B1
begin script=0x42
	end_event


; ; Map initialization code for Cavern of Ice B2a
begin script=0x43
	end_event


; ; Map initialization code for Cavern of Ice B2b
begin script=0x44
	if %Flag_Levistone_0x14 unset goto .Label_1_Flag_Levistone_0x14_Unset
	remove_trigger %Event_Levistone_Obtaining
	.Label_1_Flag_Levistone_0x14_Unset:
	end_event


; ; Map initialization code for Cavern of Ice B3a
begin script=0x45
	end_event


; ; Map initialization code for Cavern of Ice B3b
begin script=0x46
	end_event


; ; Map initialization code for Gaia
begin script=0x47
	if %Flag_Oxyale_0x1a set goto .Label_1_Flag_Oxyale_0x1a_Set
	if 0x19 unset goto .Label_2_0x19_Unset
	set_npc_event %NPC_Fairy_0xb 0x138f
	.Label_1_Flag_Oxyale_0x1a_Set:
	remove_all %Event_Fairy_Released_From_Bottle
	goto .Label_3
	.Label_2_0x19_Unset:
	npc_update 0x2 %NPC_Fairy_0xb
	.Label_3:
	end_event


; ; Map initialization code for Gaia Inn
begin script=0x48
	end_event


; ; Map initialization code for Gaia WeaponArmor Shop
begin script=0x49
	end_event


; ; Map initialization code for Gaia Item Shop
begin script=0x4a
	end_event


; ; Map initialization code for Gaia WhiteBlack Magic
begin script=0x4b
	end_event


; ; Map initialization code for Gaia Chapel
begin script=0x4c
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Citadel of Trials 1F
begin script=0x4d
	if %Flag_Rats_Tail_0x17 unset goto .Label_1_Flag_Rats_Tail_0x17_Unset
	remove_trigger %Event_Citadel_Of_Trials_Greeter
	.Label_1_Flag_Rats_Tail_0x17_Unset:
	if 0x16 unset goto .Label_2_0x16_Unset
	remove_trigger %Event_Citadel_Of_Trials_Greeter
	.Label_2_0x16_Unset:
	end_event


; ; Map initialization code for Citadel of Trials 2F
begin script=0x4e
	end_event


; ; Map initialization code for Citadel of Trials 3F
begin script=0x4f
	if %Flag_Rats_Tail_0x17 unset goto .Label_1_Flag_Rats_Tail_0x17_Unset
	remove_all %Event_Rat_Tail_Chest
	.Label_1_Flag_Rats_Tail_0x17_Unset:
	end_event


; ; Map initialization code for Mirage Tower 1F
begin script=0x50
	end_event


; ; Map initialization code for Mirage Tower 2F
begin script=0x51
	end_event


; ; Map initialization code for Mirage Tower 3F
begin script=0x52
	if %Flag_Warp_Cube_0x20 unset goto .Label_1_Flag_Warp_Cube_0x20_Unset
	remove_trigger 0x0
	.Label_1_Flag_Warp_Cube_0x20_Unset:
	end_event


; ; Map initialization code for Waterfall Cavern
begin script=0x53
	if %Flag_Warp_Cube_0x20 set goto .Label_1_Flag_Warp_Cube_0x20_Set
	set_npc_event %NPC_Robot_0x0 0x13bd
	.Label_1_Flag_Warp_Cube_0x20_Set:
	end_event


; ; Map initialization code for Dragon Caves B2
begin script=0x54
	db 0x18 0x8 0x2 0x1 0xf8 0xff 0xff 0xff
	if %Flag_Promotion_0x18 unset goto .Label_1_Flag_Promotion_0x18_Unset
	goto .Label_2
	.Label_1_Flag_Promotion_0x18_Unset:
	if %Flag_Rats_Tail_0x17 unset goto .Label_2
	set_npc_event %NPC_Bahamut_0x2 0x1396
	.Label_2:
	end_event


; ; Map initialization code for Dragon Caves B1 Bahamuts
begin script=0x55
	end_event


; ; Map initialization code for Dragon Caves B1
begin script=0x56
	end_event


; ; Map initialization code for Mt Duergar
begin script=0x57
	if %Flag_Canal_0xb set goto .Label_1_Flag_Canal_0xb_Set
	music 0x0 0x85
	db 0x2f 0x8 0x0 0x0 0xff 0x16 0x2a 0x8
	goto .Label_2
	.Label_1_Flag_Canal_0xb_Set:
	if %Flag_Canal_0xb unset goto .Label_2
	npc_update 0x2 %NPC_Nerrick_0xb
	npc_update 0x4 %NPC_Nerrick_0xb
	.Label_2:
	if %Flag_Nitro_Powder_0xa unset goto .Label_3_Flag_Nitro_Powder_0xa_Unset
	set_npc_event %NPC_Nerrick_0xb 0x1393
	.Label_3_Flag_Nitro_Powder_0xa_Unset:
	if %Flag_Mystic_Key_0x9 unset goto .Label_4_Flag_Mystic_Key_0x9_Unset
	remove_trigger %Event_Mystic_Key_Door
	.Label_4_Flag_Mystic_Key_0x9_Unset:
	if %Flag_Excalibur_0x23 unset goto .Label_5_Flag_Excalibur_0x23_Unset
	goto .Label_6
	.Label_5_Flag_Excalibur_0x23_Unset:
	if %Flag_Adamantite_0x21 unset goto .Label_6
	set_npc_event %NPC_Smyth_0x4 0x139d
	.Label_6:
	end_event


; ; Map initialization code for Western Keep
begin script=0x58
	set_npc_frame %NPC_King_Astos_0x0 0x0
	if %Flag_Mystic_Key_0x9 unset goto .Label_1_Flag_Mystic_Key_0x9_Unset
	remove_trigger %Event_Mystic_Key_Door
	.Label_1_Flag_Mystic_Key_0x9_Unset:
	if %Flag_Crystal_0x7 unset goto .Label_2_Flag_Crystal_0x7_Unset
	remove_trigger %Event_Western_Keep_King
	remove_trigger %Event_Sleeping_Elven_Prince
	goto .Label_3
	.Label_2_Flag_Crystal_0x7_Unset:
	if %Flag_Crown_0x6 unset goto .Label_4_Flag_Crown_0x6_Unset
	set_npc_event %NPC_King_Astos_0x0 0x1390
	remove_trigger %Event_Sleeping_Elven_Prince
	goto .Label_3
	.Label_4_Flag_Crown_0x6_Unset:
	remove_trigger %Event_Sleeping_Elven_Prince
	.Label_3:
	end_event


; ; Map initialization code for Marsh Cave B1
begin script=0x59
	end_event


; ; Map initialization code for Marsh Cave B2
begin script=0x5a
	end_event


; ; Map initialization code for Marsh Cave B3
begin script=0x5b
	if %Flag_Crown_0x6 unset goto .Label_1_Flag_Crown_0x6_Unset
	remove_all %Event_Crown_Chest
	.Label_1_Flag_Crown_0x6_Unset:
	if %Flag_Mystic_Key_0x9 unset goto .Label_2_Flag_Mystic_Key_0x9_Unset
	remove_all %Event_Mystic_Key_Door
	.Label_2_Flag_Mystic_Key_0x9_Unset:
	end_event


; ; Map initialization code for Flying Fortress 1F
begin script=0x5c
	end_event


; ; Map initialization code for Flying Fortress 2F
begin script=0x5d
	if %Flag_Adamantite_0x21 unset goto .Label_1_Flag_Adamantite_0x21_Unset
	remove_trigger %Event_Adamantite_Obtaining
	.Label_1_Flag_Adamantite_0x21_Unset:
	end_event


; ; Map initialization code for Flying Fortress 3F
begin script=0x5e
	end_event


; ; Map initialization code for Flying Fortress 4F
begin script=0x5f
	end_event


; ; Map initialization code for Flying Fortress 5F
begin script=0x60
	if %Flag_Air_0x22 unset goto .Label_1_Flag_Air_0x22_Unset
	remove_all %Event_Confronting_Tiamat
	remove_npc %NPC_Wind_Crystal_0x1 0x0
	remove_npc %NPC_Warp_Green_0x2 0x0
	npc_update 0x4 %NPC_Warp_Light_Green_0x5
	goto .Label_2
	.Label_1_Flag_Air_0x22_Unset:
	db 0x18 0x8 0x3 0x1 0xf8 0xff 0xff 0xff
	npc_update 0x2 %NPC_Tiamat_0x3
	npc_update 0x4 %NPC_Tiamat_0x3
	npc_update 0x4 %NPC_Warp_Green_0x2
	db 0x1c 0x4 0x2 0x3
	npc_update 0x2 %NPC_Wind_Crystal_lit_0x4
	npc_update 0x2 %NPC_Warp_Light_Green_0x5
	npc_update 0x4 %NPC_Warp_Light_Green_0x5
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	.Label_2:
	db 0x18 0x8 0x4 0x1 0xf8 0xff 0xff 0xff
	db 0x1c 0x4 0x5 0x3
	end_event


; ; Map initialization code for Matoyas Cave
begin script=0x61
	if %Flag_Jolt_Tonic_0x8 set goto .Label_1_Flag_Jolt_Tonic_0x8_Set
	if %Flag_Crystal_0x7 unset goto .Label_1_Flag_Jolt_Tonic_0x8_Set
	set_npc_event %NPC_Matoya_0x4 0x1391
	.Label_1_Flag_Jolt_Tonic_0x8_Set:
	if 0x27 unset goto .Label_2_0x27_Unset
	remove_trigger %Event_Matoyas_Plight
	goto .Label_3
	.Label_2_0x27_Unset:
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xf 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xe 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xd 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xc 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xb 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0xa 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0x9 0x8
	db 0x2f 0x8 0xa9 0x13 0xff 0x11 0x8 0x8
	.Label_3:
	end_event


; ; Map initialization code for Pravoka
begin script=0x62
	if %Flag_Ship_0x5 unset goto .Label_1_Flag_Ship_0x5_Unset
	remove_all %Event_Bikkes_Bikkeneers
	goto .Label_2
	.Label_1_Flag_Ship_0x5_Unset:
	set_npc_event %NPC_Bikke_0x2 0x13b5
	npc_update 0x2 %NPC_Man_Blue_0x3
	npc_update 0x4 %NPC_Man_Blue_0x3
	npc_update 0x2 %NPC_Man_Blue_0x4
	npc_update 0x4 %NPC_Man_Blue_0x4
	npc_update 0x2 %NPC_Man_Blue_0x5
	npc_update 0x4 %NPC_Man_Blue_0x5
	npc_update 0x2 %NPC_Woman_green_0x6
	npc_update 0x4 %NPC_Woman_green_0x6
	npc_update 0x2 %NPC_Old_Man_0x7
	npc_update 0x4 %NPC_Old_Man_0x7
	db 0x2f 0x8 0x0 0x0 0xff 0xc 0xc 0x8
	db 0x2f 0x8 0x0 0x0 0xff 0xe 0xc 0x8
	.Label_2:
	end_event


; ; Map initialization code for Pravoka Inn
begin script=0x63
	end_event


; ; Map initialization code for Pravoka Weapon Shop
begin script=0x64
	end_event


; ; Map initialization code for Pravoka Armor Shop
begin script=0x65
	end_event


; ; Map initialization code for Pravoka Item Shop
begin script=0x66
	end_event


; ; Map initialization code for Pravoka White Magic
begin script=0x67
	end_event


; ; Map initialization code for Pravoka Black Magic
begin script=0x68
	remove_trigger 0x10
	remove_trigger 0x10
	end_event


; ; Map initialization code for Pravoka Chapel
begin script=0x69
	end_event


; ; Map initialization code for Melmond
begin script=0x6a
	db 0x1c 0x4 0x0 0x1
	if %Flag_Lufienish_0x1e unset goto .Label_1_Flag_Lufienish_0x1e_Unset
	goto .Label_2
	.Label_1_Flag_Lufienish_0x1e_Unset:
	if %Flag_Rosetta_Stone_0x1c unset goto .Label_2
	set_npc_event %NPC_Unne_0x0 0x13a5
	.Label_2:
	end_event


; ; Map initialization code for Melmond Inn
begin script=0x6b
	end_event


; ; Map initialization code for Melmond Weapon Shop
begin script=0x6c
	end_event


; ; Map initialization code for Melmond Armor Shop
begin script=0x6d
	end_event


; ; Map initialization code for Melmond White Magic
begin script=0x6e
	end_event


; ; Map initialization code for Melmond Black Magic
begin script=0x6f
	end_event


; ; Map initialization code for Lufenia
begin script=0x70
	if %Flag_Lufienish_0x1e unset goto .Label_1_Flag_Lufienish_0x1e_Unset
	if %Flag_Chime_0x1f set goto .Label_1_Flag_Lufienish_0x1e_Unset
	set_npc_event %NPC_Lufenian_0xb 0x1395
	.Label_1_Flag_Lufienish_0x1e_Unset:
	end_event


; ; Map initialization code for Lufenia WhiteBlack Magic
begin script=0x71
	end_event


; ; Map initialization code for Caravan
begin script=0x72
	end_event


; ; Map initialization code for Caravan Interior
begin script=0x73
	end_event


; ; Map initialization code for Gaia White Magic 2
begin script=0x74
	end_event


; ; Map initialization code for Gaia Black Magic 2
begin script=0x75
	end_event


; ; Map initialization code for Drawbridge cutscene
begin script=0x76
	end_event


; ; Map initialization code for Ryukahn Desert cutscene
begin script=0x77
	end_event


; ; Map initialization code for Earthgift Shrine Entrance
begin script=0x78
	if %Flag_Earth_0x11 unset goto .Label_1_Flag_Earth_0x11_Unset
	remove_npc %NPC_Lich_0x1 0x0
	remove_all 0x0
	goto .Label_2
	.Label_1_Flag_Earth_0x11_Unset:
	db 0x6b 0x4 0x1 0x0
	set_npc_frame %NPC_Lich_0x1 0x0
	db 0x1c 0x4 0x1 0x2
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	.Label_2:
	end_event


; ; Map initialization code for Hellfire Chasm Entrance
begin script=0x79
	if %Flag_Fire_0x13 unset goto .Label_1_Flag_Fire_0x13_Unset
	remove_npc %NPC_Marilith_0x1 0x0
	remove_all 0x0
	goto .Label_2
	.Label_1_Flag_Fire_0x13_Unset:
	db 0x6b 0x4 0x1 0x0
	set_npc_frame %NPC_Marilith_0x1 0x0
	db 0x1c 0x4 0x1 0x1
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	.Label_2:
	end_event


; ; Map initialization code for Lifespring Grotto Entrance
begin script=0x7a
	if %Flag_Water_0x1d unset goto .Label_1_Flag_Water_0x1d_Unset
	remove_npc %NPC_Kraken_0x1 0x0
	remove_all 0x0
	goto .Label_2
	.Label_1_Flag_Water_0x1d_Unset:
	db 0x6b 0x4 0x1 0x0
	set_npc_frame %NPC_Kraken_0x1 0x0
	db 0x1c 0x4 0x1 0x2
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	.Label_2:
	end_event


; ; Map initialization code for Whisperwind Cove Entrance
begin script=0x7b
	if %Flag_Air_0x22 unset goto .Label_1_Flag_Air_0x22_Unset
	remove_npc %NPC_Tiamat_0x1 0x0
	remove_all 0x0
	goto .Label_2
	.Label_1_Flag_Air_0x22_Unset:
	db 0x6b 0x4 0x1 0x0
	set_npc_frame %NPC_Tiamat_0x1 0x0
	db 0x1c 0x4 0x1 0x2
	db 0x18 0x8 0x1 0x1 0xf8 0xff 0xff 0xff
	.Label_2:
	end_event


